version: '3'
services:
  orderservice:
    build:
      context: ./OrderService.API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - RABBITMQ_CONNECTIONSTRING=ampq://localhost
